### PR TITLE
Breadcrumbs modification

### PR DESCRIPTION
**Pull request by BolotskyDev**
**Describe the changes**

This PR brings modification to a breadcrumb blog of the doc pages, see screenshot below

**Steps to test**
1. Run the project 
2. Open any nested doc page
3. See breadcrumbs

**Screenshots**
image

### CODE REVIEW

**Comment by BolotskyDev** [comment]
@ppcano Please, do some skim checks before it hits even `staging` since bugs in breadcrumbs have strong negative impact on ux

**Comment by ppcano** [comment]
@BolotskyDev Everything looks good except the docs of the Javascript API.

Screen Shot 2020-06-23 at 5 37 09 PM
Screen Shot 2020-06-23 at 5 37 04 PM

**Comment by BolotskyDev** [comment]
@ppcano Well, that is the same content we see in sidebar. Do you want me to strip method args?

**Comment by ppcano** [comment]
@BolotskyDev If possible, the breadcrumb should be:

 `Javascript API` > `k6/crypto` > `createHash( algorithm )`

`Javascript API` > `k6` > `check( val, sets, [tags] )`

**Comment by BolotskyDev** [comment]
@ppcano Alright, you can check out the formatting again

**Comment by ppcano** [comment]
@BolotskyDev 

The Examples page is wrong

Screen Shot 2020-06-24 at 10 59 49 AM

Besides this issue, LGTM

**Pull request merged**
