### PR TITLE
Breaking change: mdx processing update

### PR DESCRIPTION
**Pull request by BolotskyDev**
**Describe the changes**
This PR brings a long-awaited update to the way we process mdx: `Code` and `CodeGroup` now being rendered via native mdx renderer as the opposite to previously hot replacement which caused performance issues and was blocking some features to come out.

**Verbose**
- migrated from `gatsby-remark-prismjs` to `prismjs-react-renderer` for max flexibility during custom code block render
- refactored `Code` and `CodeGroup` components
- added postponed earlier collapse/expand mechanism for `Code` component ([task in Notion](https://www.notion.so/pixelpoint/Add-scrolling-option-to-code-blocks-b9f7e7d073e04e8ea5e72152ad9160cd))
- added `CodeInline` component
- updated code blocks usage in every `.md` file

**Side**
- Fixed `Blockquote` component styling bugs described [here](https://github.com/loadimpact/k6-docs/commit/b657e01b7ca3980337571682c839f15a35814008#commitcomment-43306583)
- Since `Cloud API` section has been published, I've enabled Algolia indexing for them back 

**Steps to test**
1. Skim check the diff in `md` files, make sure nothing important got deleted accidentally
2. Make sure it works locally both in dev and prod 
3. Make some random page with code blocks checks, see everything is working as expected
4. Find any page with large code blocks, test expand/collapse mechanism (or just copy past content of a small one temporarily)

### CODE REVIEW

**Comment by ppcano** [comment]
@BolotskyDev Please, can you fix the conflicts to test it

**Comment by BolotskyDev** [comment]
@ppcano sorry, I don't see a single one in GitHub UI, just `merging is blocked`, I'll align it with latest changes in master shortly 👍

**Comment by BolotskyDev** [comment]
@ppcano Okay, I've checked everything again and aligned with `master` branch, you are good to give it a shot ! 👍

**Comment by ppcano** [comment]
@BolotskyDev 

> Since Cloud API section has been published, I've enabled Algolia indexing for them back

No. It hasn't been published in `production`.


> This branch cannot be rebased due to conflicts
It looks conflicts are still present.

**Comment by BolotskyDev** [comment]
> No. It hasn't been published in `production`.
Okay, I'll hide them back
> It looks conflicts are still present.
I see, there are some git reference problems in this PR since I've made changes based on now deleted `develop`. I am about to rebase it manually on my local machine, that should help 👌

**Comment by BolotskyDev** [comment]
Though it is still not clear for me why don't I see info on conflicts even if I am not authorised to merge the branch, that is really annoying 🙄 
image

**Comment by ppcano** [comment]
@BolotskyDev Try now. You didn't have `master` permission

**Comment by BolotskyDev** [comment]
@ppcano Thanks, now I am able to sport the problem: 

Default Github's behavior is to `merge` the branch, and that action actually is available: 
image

But if I am switching to `rebase` I immediately see the problem:
image

So, back then I had no privileges to change the method and saw no problems you've been seeing all along 🙂 

Anyway, rebasing commit is coming 🚀

**Comment by BolotskyDev** [comment]
This PR is closed due to necessity in its recreation: don't want to mess up with commit history.

**Pull request closed without merging**
