### PR TITLE
Feature: Azure Monitor integration for Cloud APM

### PR DESCRIPTION
**Pull request by mostafa**
This PR restructures the `Cloud APM` doc and introduces 3 pages:
1. Cloud APM top-level doc about the feature, common configuration parameters, ....
2. DataDog integration doc.
3. Azure Monitor integration doc.

**As of Jan. 2020, all configuration parameters are in camel case.**

### CODE REVIEW

**Comment by ppcano** [comment]
I would name it as `Azure Monitor` instead of `Microsoft Azure Monitor`.

**Review by simskij — APPROVED** [review]
Great article! 👏🏼 Some nitpicks below.

**Review by simskij — CHANGES_REQUESTED** [review]
Misclicked approve 😭

**Comment by mostafa** [comment]
Thanks @simskij for the review! I applied your comments.

**Pull request merged**
