### PR TITLE
Docs file tree restructuring

### PR DESCRIPTION
**Pull request by BolotskyDev**
**Describe changes**
This PR brings file tree restructuring to `data/markdown` section, which gets all currently missing images back. Side: updated contributing format file.

**Reason**
After merging #71 @ppcano reported missing images on a number of pages. After a short investigation it turned out, that #71 has almost nothing to do with that - the problem is in images position in file tree. I don't know why it even worked before, it really shouldn't have been. 

Here is what I mean:

https://staging.k6.io/docs/using-k6/metrics - one of the reported page. Look at one of the missing images path:
image
It requires `custom-metrics.png` in `/images`. But `/images` has no such file:
image

That is the cause. 

**Changes, verbose**
- reorganized piles of images in clusters into multiple article-related folders
- checked every image for usage cases - apparently there are plenty of images that are not being used anymore. I've marked them `[unused]-%old_name%`. 
- adjusted a bunch of paths like this: `[](images/...)` -> `[](/images/...)` and replaced some of `%`-including path with kebab-case alternatives. Actually, that is interesting: I have no idea why, but some of the images are perfectly working with path like `[image](images/01%image%folder/image.png)`, but in other folders they just won't and require to be adjusted to `[image](/images/01-image-folder/image.png)`. I've reflected this behaviour in contributing file format. 
- finally I've checked every single page in dev and prod env to make sure no broken images are left

**Steps to test**

- check that I didn't make some severe mutations to articles content somewhere
- pull the changes, run `npm run build && npm run serve`
- go to `localhost:9000/docs`
- random check articles, see that images are indeed there

### CODE REVIEW

**Comment by ppcano** [comment]
@BolotskyDev  Following your instructions. the images are not loaded.

**Comment by BolotskyDev** [comment]
@ppcano how bizarre! Please, run in your terminal:
`gatsby clean && rm -rf /node_modules && npm i && npm run build && npm run serve`

Probably, stale data / deps problem, since I am definitely able to see images in bot dev/prod env. Let me know if you have had any luck with this! I'll think of something else in case of a negative scenario, probably will tweak circleci config again to quick test it in `staging`.

**Comment by ppcano** [comment]
@BolotskyDev unfortunately, it didn't solve the problem for me.

Screen Shot 2020-08-20 at 12 43 14 AM

It looks the fonts are also not loaded.

**Comment by BolotskyDev** [comment]
@ppcano I've tweaked config to watch the changes in staging - it checks out definitely, e.g.
https://staging.k6.io/docs/using-k6/checks 
https://staging.k6.io/docs/using-k6/metrics
full of pictures ! 

Honestly, I have no idea what is going on by your side. Only one and probably stupid suggestion - are you sure you pulled the changes correctly? Because apart from that nothing could be causing problems, you basically reinstalled and rebuild everything from the ground up using that chained command.

**Comment by ppcano** [comment]
I think it was my mistake, and I was on the wrong branch. Apologies.

Merged and complemented with https://github.com/loadimpact/k6-docs/commit/a716f66aaacf8e458aa09bbcc18bea9b63a808ad

I will test it in `staging` and we can release it next week.

**Pull request merged**
