### PR TITLE
Add OAuth example

### PR DESCRIPTION
**Pull request by mostafa**
Hey @robingustafsson,

Is this OK, or should I add more?

### CODE REVIEW

**Review by ppcano — CHANGES_REQUESTED** [review]
I think it should be its own example. Not integrated with HTTP Authentication.

I'll create a final read more link to the blog post.

**Comment by mostafa** [comment]
@ppcano Then, does this means that I should reorder all examples?

**Comment by ppcano** [comment]
@mostafa `may the force be with you`

**Comment by mostafa** [comment]
@ppcano I've added a separate OAuth page and rearranged the others.

**Pull request merged**
